== Subject

The OGC Interoperable Simulation and Gaming Year 2 Sprint advanced the use of relevant OGC and https://www.khronos.org/[Khronos Group] cite:[Khronos] standards in the modeling, simulation, and training communities through capability development, compatibility testing, and gap analysis. Of particular interest was the use of glTF models, game engines, and 3rd-party mobile device libraries for the display and interaction with OGC data and APIs.

== Executive Summary

The Interactive Simulation and Gaming (ISG) Year 2 Sprint ("Sprint") was undertaken by OGC under the https://www.ogc.org/ogc/programs/ip[OGC Innovation Program] to investigate and analyize the capability of using a combination of OGC and non-OGC standards:
 
 * https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#contents[glTF] cite:[glTF_Core] in particular;
 * Widely adopted 3rd party display engines (Unity and Unreal Engine in particular); 
 * OGC current and upcoming Standards (in particular GeoVolumes, GeoPose, SensorThings, and MovingFeatures);
 * Future alignment with emerging new technologies and CDB.

The primary non-OGC standard under consideration was https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#contents[glTF]. The use of glTF was also successfully investigated in ISG Year 1 Sprint. 3rd-party display engines included not only Unity and Unreal Engine, but the https://en.wikipedia.org/wiki/ARCore[ARCore] cite:[ARCore] and https://en.wikipedia.org/wiki/IOS_11#Developer_APIs[ARKit] cite:[ARKit] mobile device augmented reality libraries. 

The OGC existing and emerging standards of interest include CDB (1.x and 2.0), GeoVolumes, GeoPose, SensorThings, and MovingFeatures. CDB is of special interest in that an optional goal is alignment of new technology with a future release of CDB, especially using glTF as an additional modeling format.

OGC has partnered with https://khronos.org[The Khronos Group] on two Sprints (Year 1 and Year 2). Both organizations worked diligently to advance glTF to meet the needs of current and future users while ensuring support to previous activities. Both organizations are investing in the development of new and future technologies.

=== Operation

The period of performance for the Sprint was two months from kickoff to submission of Sprint participant reports. The actual coding effort was scheduled for two weeks in June 2021 on either side of the June quarterly OGC Member Meeting. The entire effort was planned and executed virtually.

Two CDB structured datastores were made available to all participants - the San Diego and New York CDB datastores. Additionally, the participants accessed eight other datasets. The use of other datasets was unexpected and the list is documented in <<Datasets-Used-ISG-Year-2-Sprint,Appendix C: Datasets Used in ISG Year 2 Sprint>>. The Sprint participants were (in alphabetical order): <<Cesium,Cesium>>, <<Ecere,Ecere>>, <<FlightSafety,FlightSafety>>, <<InfoDao,InfoDao>>, <<SimBlocks,SimBlocks.io>>, and <<Steinbeis,Steinbeis>>. All participants were OGC members and had prior experience participating in OGC projects.

=== Accomplishments

Most of the Sprint participants partnered with at least one other participant for some portion of their work. The participants addressed a wide-range of issues described in the https://portal.ogc.org/files/?artifact_id=96942[OGC ISG Year 2 Sprint: Call for Participation (CFP)] cite:[CFP_ISG_2]. This is shown in <<table_scenario-participant>>. The wide range of problems addressed plus an agreement on cross-over snags provided confidence that the problem-space was covered and individual results are generally applicable.

* The data conversion process between various formats used by CDB datastores is mostly understood. Future efforts should be focused on operational improvements for specific scenarios.
* glTF is sufficiently capable to support static GeoTypical and GeoSpecific models contained in a CDB datastore.
* Game engines (Unreal Engine and Unity) were demonstrated to work with data based on an existing OGC encoding standard.
* OGC structured and encoded data and APIs can be integrated into mobile apps using ARCore and ARKit.
* Seamless and smooth transitions can be done when moving from the outdoors to an indoor environment and back out.

=== Issues

A few issues were discovered during the Sprint. Mostly these were related to difficulties or differences with third-party applications. One issue may be a result of inccomplete 3D Tiles specification or a misunderstanding in a common implementation. All of the issues are documented in <<discovered-issues,Discovered Issues>> in the <<Findings,Findings>> chapter. The most important ones are listed below.

* <<CesiumJS-Prevents-Refinement,Error in specification descriptions or interpretation of empty tiles in 3D Tiles.>>
* <<general-results,Sprint was scheduled to be interrupted by OGC Member Meeting preventing smooth and continuous development during the Sprint.>>
* <<OpenFlight-Different-Coordinate-System,3D applications may use different coordinate systems.>>
* <<Unity-Development-Issues,Some 3rd-party software related to game engines is not reliable or performant as needed.>>
* <<moving-models,The ability to handle moving features is a hard problem.>>

=== Recommendations

This Sprint generated seven general recommendations. Each recommendation derived from one or more of the issues identified by the participants. The recommendations are listed here in order of importance with the details linked from each recommendation.

1. <<recommendation-cdb-gltf,Recommendation #5:>> Include glTF as an optional prototype modeling format in an upcoming release of CDB.
	
2. <<recommendation-track-xr,Recommendation #6:>> Use a Sprint to investigate integration of SensorThings and GeoPose to remotely track moving objects or people of interest displaying the results in a virtual or augmented reality environment.
	
3. <<recommendation-indoor-outdoor,Recommendation #7:>> Use a Sprint to display a building environment with indoor and outdoor components. The display environment needs to include extensive use of metadata and IoT (SensorThings API) to highlight features not readily visibly.

4. <<recommendation-catalog-datasets,Recommendation #3:>> OGC should develop a catalog of datasets for future projects and members.

5. <<recommendation-Khronos,Recommendation #4:>> Increase communication between OGC and Khronos Group to speed up geospatial requirements for glTF and adoption of glTF in the geospatial community.
	
6. <<recommendation-member-meeting,Recommendation #2:>> Do not have the Sprint work week(s) immediately before a member meeting.

7. <<recommendation-er-work,Recommendation #1:>> Allow at least 3 months from the conclusion of the Sprint work to write, edit, and review the final Engineering Report.


===	Document contributor contact points

All questions regarding this document should be directed to the editor or the contributors:

*Contacts*
[width="80%",options="header",caption=""]
|====================
|Name |Organization | Role
|Leonard Daly                    | Daly Realism representing Khronos Group | Editor & Contributor
|Rollin Philips                  | Open Geospatial Consortium | Editor & Contributor
|Sean Lilley                     | Cesium | Contributor
|Sam Suhag                       | Cesium | Contributor
|Michala Hill                    | Cognitics/SOCOM | Sponsor support
|Jerome St-Louis                 | Ecere | Contributor
|Diego Caraffini                 | Ecere | Contributor
|Patrick Dion                    | Ecere | Contributor
|Spencer Berg                    | FlightSafety | Contributor
|Ryan Franz                      | FlightSafety | Contributor
|Aaron Williams                  | FlightSafety | Contributor
|Joshua Rentrope                 | InfoDao | Contributor
|Jordan Dauble                   | SimBlocks.io | Contributor
|Glenn Johnson                   | SimBlocks.io | Contributor
|Volker Coors                    | Steinbeis, HFT Stuttgart | Contributor
|Thunyathep Santhanavanich (Joe) | Steinbeis, HFT Stuttgart | Contributor
|Athanasios Koukofikis           | Steinbeis, HFT Stuttgart | Contributor
|Rushikesh Padsala               | Steinbeis, HFT Stuttgart | Contributor
|Patrick Würstle                 | Steinbeis, HFT Stuttgart | Contributor
|====================


// *****************************************************************************
// Editors please do not change the Foreword.
// *****************************************************************************
=== Foreword

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
