== Terms and definitions

[NOTE]
._**Draft**_
====
This section is not complete. The bulleted lists will be turned into prose with references to the detailed descriptions. Additional items may be added based on additional reviews of the participant material.
====


For the purposes of this report, the definitions specified in Clause 4 of the OWS Common Implementation Standard https://portal.opengeospatial.org/files/?artifact_id=38867&version=2[OGC 06-121r9] shall apply. In addition, the following terms and definitions apply.

[NOTE]
._**Structure**_
====
Many of these are acronyms and not really _terms_. Should the acronums be included here or not?
====


&#9679; 3D Tiles ::

 _tbd_

&#9679; 3D Tiles Next ::

 _tbd_ Links to https://github.com/CesiumGS/3d-tiles/blob/3d-tiles-next/3D_TILES_NEXT.md

&#9679; CDB ::

 _tbd_
 
&#9679; B3DM ::

_tbd_

&#9679; DIS ::

 Distributed Interactive Simulation

&#9679; DOF(s) ::

 Degrees of Freedom. Full freedom in space has six degrees of freedom - left/right, front/back, up/down, roll, pitch, and yaw.

&#9679; FlightSafety ::

_This is a participant, not a term_

&#9679; GeoPackage ::

 _tbd_ 

&#9679; GeoSpecific ::

 A 3D model of an object that has a specific place on Earth. Examples include Eifel Tower, US Capitol, Mt. Rushmore, and many other objects that are unique and may be used to immediately identify a location and potentially time.

&#9679; GeoTypical ::

 A 3D model of an object whose existance does not identify a location and where the model may be used repeatedly. Examples include trees, most warehouses, and many residential buildings. 

&#9679; glTF ::

The 3D model standard from the Khronos Group. It stands for "graphics language Transmission Format". The V2.0 standard is https://github.com/KhronosGroup/glTF/tree/master/specification/2.0[documented]. The standard is in the process of becoming an ISO Standard.

&#9679; GTModel ::

 _tbd_ 

&#9679; HLA ::

 _tbd_ 

&#9679; I3DM ::

 _tbd_ 

&#9679; IoT ::
 Internet of Things

&#9679; LOD ::

Level Of Detail. A highly detailed model may be created to display at reduced detail when the scene camera is far away. The model typically defines the number of levels, the detail shown at each level, and the applicable viewing range.

&#9679; NVG ::

 _tbd_ 

&#9679; OpenFlight ::

A data modeling language...  _tbd_ 
 
&#9679; PBR ::
Physically Based Rendering. This is a means for calculating the appearance of a model based on a number of physical parameters including metal-roughness, normals, and transmission. glTF uses this model for rendering.

&#9679; TIFF ::

Tagged Image File Format. This format is used for storing raster graphics images. It is a container format that can store multiple diffrent image formats. Images stored as TIFF files frequently are uncompressed or lossless-ly compressed. See also https://en.wikipedia.org/wiki/TIFF[Wikipedia - TIFF]. 
 


[NOTE]
._**Question**_
====
RP: How crazy do I go with Terms, like XML, PNG and the likes of _obvious_ internet jargon isn't needed right?
====


&#9679; term name ::

 text of the definition

&#9679; term name|synonym  ::

 text of the definition


===	Abbreviated terms

.NOTE: The abbreviated terms clause gives a list of the abbreviated terms and the symbols necessary for understanding this document. All symbols should be listed in alphabetical order. Some more frequently used abbreviated terms are provided below as examples.

* COM	Component Object Model
* CORBA	Common Object Request Broker Architecture
* COTS	Commercial Off The Shelf
* DCE	Distributed Computing Environment
* DCOM	Distributed Component Object Model
* IDL	Interface Definition Language
