== Terms and definitions

[NOTE]
._**Draft**_
====
This section is not complete. The bulleted lists will be turned into prose with references to the detailed descriptions. Additional items may be added based on additional reviews of the participant material.
====


For the purposes of this report, the definitions specified in Clause 4 of the OWS Common Implementation Standard https://portal.opengeospatial.org/files/?artifact_id=38867&version=2[OGC 06-121r9] shall apply. In addition, the following terms and definitions apply.

[NOTE]
._**Structure**_
====
Many of these are acronyms and not really _terms_. Should the acronums be included here or not?
====


&#9679; 3dsMax ::

 _tbd_ 
 
&#9679; 3D Tiles ::

 _tbd_

&#9679; 3D Tiles Next ::

 _tbd_ Links to https://github.com/CesiumGS/3d-tiles/blob/3d-tiles-next/3D_TILES_NEXT.md

&#9679; ArcGIS ::

 _tbd_ 
 
&#9679; CDB ::

 _tbd_
 
 &#9679; CDB X ::

 _tbd_  
 
&#9679; OpenFlight ::

 _tbd_ 
 
&#9679; COLLADA ::
 
 A 3D model format that supports private extensions.
 
&#9679; CityGML ::

 _tbd_ 

&#9679; EOS ::

 _tbd_ 
 
&#9679; Feature Manipulation Engine ::

 _tbd_ 

 &#9679; GeoPackage ::

 _tbd_ 

&#9679; GeoSpecific ::

 A 3D model of an object that has a specific place on Earth. Examples include Eifel Tower, US Capitol, Mt. Rushmore, and many other objects that are unique and may be used to immediately identify a location and potentially time.

&#9679; GeoTypical ::

 A 3D model of an object whose existance does not identify a location and where the model may be used repeatedly. Examples include trees, most warehouses, and many residential buildings. 
 _tbd_  
 
&#9679; glb ::

 See _glTF_.

&#9679; glTF ::

The 3D model standard from the Khronos Group. It stands for "graphics language Transmission Format". The V2.0 standard is https://github.com/KhronosGroup/glTF/tree/master/specification/2.0[documented]. The standard is in the process of becoming an ISO Standard. A glTF model may be represented in multiple files with the primary file having the extension **.gltf**; or typically a single file with the extension **.glb**.

&#9679; GNOSIS ::

 Ecere's geospatial client

&#9679; GTModel ::

 See _GeoTypical_

&#9679; One World SDK ::

SimBlocks.io software development kit for handling geospatial data in Unity.
 
&#9679; OpenFlight ::

A data modeling language.
 
&#9679; OSG Software ::

 _tbd_ 
 
&#9679; SensorThings API ::

 _tbd_ 
 
&#9679; skp ::

 _tbd_ 
 
&#9679; TinyGLTF ::

An open source software library that handles glTF files.
 
&#9679; Trimble Sketchup ::

 _tbd_ 
 


[NOTE]
._**Question**_
====
RP: How crazy do I go with Terms, like XML, PNG and the likes of _obvious_ internet jargon isn't needed right?
====


&#9679; term name ::

 text of the definition

&#9679; term name|synonym  ::

 text of the definition


===	Abbreviated terms

.NOTE: The abbreviated terms clause gives a list of the abbreviated terms and the symbols necessary for understanding this document. All symbols should be listed in alphabetical order. Some more frequently used abbreviated terms are provided below as examples.

* COTS	Commercial Off The Shelf

* DCE	Distributed Computing Environment

* IDL	Interface Definition Language

* B3DM _tbd_

* COTS Commercial Off The Shelf

* CNAM XML

* DIIL Disconnected, Interrupted, Intermittent, Low-Bandwidth

* DIS  Distributed Interactive Simulation

* DOF(s) Degrees of Freedom. Full freedom in space has six degrees of freedom - left/right, front/back, up/down, roll, pitch, and yaw.

* E3D Ecere's 3D model format

* FLIR Forward looking InfraRed

 _tbd_ 
 
* HLA ::

 _tbd_ 

* I3DM ::

 _tbd_ 

* IoT  Internet of Things

* LOD Level Of Detail. A highly detailed model may be created to display at reduced detail when the scene camera is far away. The model typically defines the number of levels, the detail shown at each level, and the applicable viewing range.

* MModels Moving Models

* MOVINT Movement Intelligence

* NVG Night vision goggles

&#9679; NGA GRiD ::

* PBR Physically Based Rendering. This is a means for calculating the appearance of a model based on a number of physical parameters including metal-roughness, normals, and transmission. glTF uses this model for rendering.

* SWIR Short-Wave InfraRed. The spectrum of electromagnetic energy with wavelength longer than visible red, but shorter than thermal energy.
 
* TIFF Tagged Image File Format. This format is used for storing raster graphics images. It is a container format that can store multiple diffrent image formats. Images stored as TIFF files frequently are uncompressed or lossless-ly compressed. See also https://en.wikipedia.org/wiki/TIFF[Wikipedia - TIFF]. 
 
* X3D Extensive 3D Graphics - an ISO standard for storing, transmitting, and displaying 3D models. See https://www.web3d.org/ for more details.

* XR Extended Reality. This term encompases the entire specturm from fully **V**irtual **R**eality (everthing computer rendered), through **A**ugmented **R**eality (some objects comptuer rendered , and composed with camera data), to **R**eal **R**eality (complete physical space and objects).

