== Terms and definitions

For the purposes of this report, the definitions specified in Clause 4 of the OWS Common Implementation Standard https://portal.opengeospatial.org/files/?artifact_id=38867&version=2[OGC 06-121r9] shall apply. In addition, the following terms and definitions apply.


&#9679; https://www.autodesk.com/products/3ds-max/overview[3dsMax] cite:[Autodesk_3dsMax] ::

 A 3D modeling and rendering software application from Autodesk.
 
&#9679; 3D Tiles ::

 A data structure specified in the OGC 3D Tiles Community Standard. See <<references,References>>.

&#9679; 3D Tiles Next ::

 https://github.com/CesiumGS/3d-tiles/blob/3d-tiles-next/3D_TILES_NEXT.md[Cesium's proposed next generation of 3D Tiles] cite:[Tile3D_2].

&#9679; https://www.esri.com/en-us/arcgis/about-arcgis/overview[ArcGIS] cite:[Esri_ArcGIS]::

 A software platform from Esri that offers capabilities for specifyng and applying location-based analytics.
 
&#9679; CDB cite:[CDB_]::

 The OGC CDB standard that defines a model and rules for structuring a single virtual representation of the earth. This term is sometimes used to refer to a dataset at a particular location (e.g., <<table_annex-datasets,San Diego CDB>>)
 
 &#9679; CDB X ::

 The next major version of CDB. Work on CDB-X is in progress and many core requirements classes have been specified and documented. 
 
&#9679; COLLADA ::
 
 A 3D model format that supports private extensions.
 
&#9679; CityGML cite:[CityGML] ::

 The OGC open data model and file format for the storage and exchange of virtual 3D city models/data. See <<references,References>>.

&#9679; Feature Manipulation Engine ::

 A software application from Safe Software that transforms data and formats.

 &#9679; GeoPackage cite:[GeoPackage] ::

An open, standards-based, platform-independent portable, self-describingm compact format for storing and transferring geospatial information. See <<references,References>>.

&#9679; GeoSpecific ::

 A 3D model of an object that has a specific place on Earth. Examples include the Eiffel Tower, the US Capitol, Mt. Rushmore, and many other objects that are unique and may be used to immediately identify a location and with potentially time information.

&#9679; GeoTypical ::

 A 3D model of an object whose existence does not identify a location and where the model may be used repeatedly. Examples include trees, most warehouses, and many residential buildings. 
 
&#9679; glb ::

 See _glTF_.

&#9679; glTF ::

The 3D model standard from the Khronos Group. It stands for "graphics language Transmission Format". The V2.0 standard is https://github.com/KhronosGroup/glTF/tree/master/specification/2.0[documented]. The standard is in the process of becoming an ISO Standard. A glTF model may be represented in multiple files with the primary file having the extension **.gltf**; or typically a single file with the extension **.glb**.

&#9679; GNOSIS ::

 Ecere's geospatial client

&#9679; GTModel ::

 See _GeoTypical_

&#9679; One World SDK ::

SimBlocks.io software development kit for handling geospatial data in the Unity real-time 3D engine.
 
&#9679; OpenFlight cite:[OF_] ::

 A 3D geometry modeling and scene description language and file format used for real-time visual simulation of 3D terrain features and moving models.
 
&#9679; OpenSceneGraph ::

An open-source 3D graphics software library used for a variety of application development.
 
&#9679; SensorThings API cite:[SensorThings] ::

An OGC API Standard that defines an open, geospatial-enabled and unified way to interconnect the Internet of Things (IoT) devices, data, and applications over the Web.. See <<references,References>>.
 
&#9679; skp ::

 See _Trimble Sketchup_.
 
&#9679; TinyGLTF ::

An open source software library that handles glTF files.
 
&#9679; Trimble Sketchup ::

 A web-based 3D modeling environment that is frequently used for building models.

===	Abbreviated terms

* *COTS* - Commercial Off The Shelf

* *DCE* - Distributed Computing Environment

* *IDL* - Interface Definition Language

* *B3DM* - Batched 3D Model

* *COTS* - Commercial Off The Shelf

* *CName* - Colonized Name - an XML term for a particular type of string.

* *DIIL* - Disconnected, Interrupted, Intermittent, Low-Bandwidth

* *DIS* - Distributed Interactive Simulation

* *DOF(s)* - Degrees of Freedom. Full freedom in space has six degrees of freedom - left/right, front/back, up/down, roll, pitch, and yaw.

* *E3D* - Ecere's 3D model format

* *EOS* - Earth Observing System

* *FLIR* - Forward looking InfraRed

* *HLA* - High Level Architecture

* *I3DM* - Instanced 3D Model

* *IoT* - Internet of Things

* *LOD* - Level Of Detail. A highly detailed model may be created to display at reduced detail when the scene camera is far away. The model typically defines the number of levels, the detail shown at each level, and the applicable viewing range.

* *MModels* - Moving Models

* *MOVINT* - Movement Intelligence

* *NVG* - Night vision goggles

* *NGA* - GRiD National Geospatial-Intelligence Agency Geospatial Repository and Data Management

* *OSG* - OpenSceneGraph
 
* *PBR* - Physically Based Rendering. This is a means for calculating the appearance of a model based on a number of physical parameters including metal-roughness, normals, and transmission. glTF uses this model for rendering.

* *SWIR* - Short-Wave InfraRed. The spectrum of electromagnetic energy with wavelength longer than visible red, but shorter than thermal energy.
8 
* *TIFF* - Tagged Image File Format. This format is used for storing raster graphics images. It is a container format that can store multiple different image formats. Images stored as TIFF files frequently are uncompressed or lossless-ly compressed. See also https://en.wikipedia.org/wiki/TIFF[Wikipedia - TIFF] cite:[TIFF]. 
 
* *X3D* - Extensive 3D Graphics - an ISO standard for storing, transmitting, and displaying 3D models. See https://www.web3d.org/standards cite:[WEB3D] for more details.

* *XR* - Extended Reality. This term encompasses the entire spectrum from fully **V**irtual **R**eality (everything computer rendered), through **A**ugmented **R**eality (some objects computer rendered, and composed with camera data), to **R**eal **R**eality (complete physical space and objects).
