[[Findings]]
== Findings ...

[NOTE]
._**Draft**_
====
This section is not complete. The bulleted lists will be turned into prose with references to the detailed descriptions. Additional items may be added based on additional reviews of the participant material.
====

=== Introduction

These findings all come from comments (written or verbal) from the participants. These represent either items that were deemed important by the participants. The information here comes from achieved results, not unachieved stretch goals.

=== Aspects of Investigation

Each participant was free to choose which one (or more) scenarios to pursue. Four scenarios were discussed in the https://portal.ogc.org/files/?artifact_id=96942[Call for Proposals]. Participants could also define their own scenario. Compensentation was based on the number of chosen scenarios and the depth to which each chosen scenario was pursued. OGC reviewed each participant’s proposal and suggested revisions to better align with the goals of the Sprint, the interest of the Sponsor, and the coverage by the other participants. <<table_scenario-listing>> provides a summary description of the selected scenarios. <<table_scenario-participant>> shows the coverage of scenarios by the participants.

[#table_scenario-listing,reftext='{table-caption} {counter:table-num}']
.A summary of the scenarios used during Sprint Year 2. Scenarios 1-4 were defined in the Call for Participation. Cesium proposed in-kind work as a modification of Scenario 4.
[cols="^1,6",width="80%",options="header",align="center"]
|===
| Scenario | Summary Description

| 1A | Develop efficient on-demand conversion from on OGC 3D format to another. 
| 1B | Develop efficient batch conversion from on OGC 3D format to another. 
| 2  | Integrate indoor and outdoor displays with metadata.
| 3  | Integrate animated transportation networks with 3D tiled display.
| 4  | Perform actual-use gap analysis on OpenFlight and glTF core + modules.
| 4C | Develop specific glTF extensions to support needed capabilities in CDB.
|===

[#table_scenario-participant,reftext='{table-caption} {counter:table-num}']
.A summary of the scenarios used during Sprint Year 2. Scenarios 1-4 were defined in the Call for Participation. Cesium proposed in-kind work as a modification of Scenario 4.
[cols="<3,^1,^1,^1,^1,^1,^1",width="80%",options="header",align="center"]
|===
|             6+| Scenario
| *Participant* | *1A* | *1B* | *2* | *3* | *4* | *4C*

|<<Cesium,Cesium>>             | | | | | | *&#10003;*
|<<Ecere,Ecere>>               | *&#10003;* | *&#10003;* | *&#10003;* | | | 
|<<FlightSafety,FlightSafety>> | | | | ^|*&#10003;* | 
|<<InfoDao,InfoDao>>           | *&#10003;* | *&#10003;* | | | |
|<<SimBlocks,SimBlocks>>       | | *&#10003;* | | *&#10003;* | | 
|<<Steinbeis,Steinbeis>>       | | | *&#10003;* | *&#10003;* | | | 
|===

==== Cooperative Efforts

Unlike the http://docs.ogc.org/per/20-087.html[ISG Sprint Year 1] or the https://docs.ogc.org/per/20-030.html[GeoVolumes Pilot], this Sprint did not require or make major use of Technology Integration Experiment (TIE). There was still substantial cooperation between some of the participants that need to be recognized. The following list is presented without order.

* *Cesium* and *FlightSafety* cooperated on the understanding and development of glTF extensions and OpenFLight feature analysis.

* *Ecere* and *Steinbeis* worked together on the indoor/outdoor display capabilities required by Scenario 2.

* *Cesium's* geospatial client, CesiumJS, was used by *Ecere*, *FlightSafety*, *Steinbeis*, and *Cesium*.

=== Results

==== General Results

** Don't split a 2-week sprint by the member's meeting
** Best to entirely avoid member's meeting week
** glTF needs additional work to fully support geospatial work and CDB in particular


==== Discovered Inconsistecies

Various inconsistencies with various aspect or external items were discovered. These include OGC Standards, OGC data, modeling standards, and software. Some of the inconsistencies are documented, and others reflect documentation that needs improving.

* Ecere
** Minor mistake in prototyped CDB X dataset
** Error in CesiumJS interpertation of empty tiles (a clarification may be needed in 3D Tiles specification)
* FlightSafety
** glTF coordinate reference system is different than OpenFlight or 3dsMax
*** https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#coordinate-system-and-units[glTF is a right-handed system with Y-up]
*** OpenFlight is a left-handed system with Z-up (Volume 6: OGC CDB Rules for Encoding Data using OpenFlight)
*** https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/CloudHelp/cloudhelp/2020/ENU/3DSMax-Basics/files/GUID-0F3E2822-9296-42E5-A572-B600884B07E3-htm.html#GUID-0F3E2822-9296-42E5-A572-B600884B07E3[3DS Max is a right-handed system with Y-up]

* SimBlocks.io
** Some open source software is not as reliable or performant as needed


==== Game Engine Interface

The following participants incorporated game engine (Unreal or Unity) into the client display of geospatial data while working on their chosen scenarios.

* **InfoDao** displayed results in Unity while investigating moving models

* **SimBlocks.io** used Unreal and Unity game engines as the client display when batch converting CDB and other geospatial data.

* **Steinbeis** achieved an indoor / outdoor scenario that incorporated real-time interface to SensorThings API and drone-view that allowed a merged over-the-shoulder and altitude view of the 3D environment. They integrated display capabilities from Unreal Engine (e.g., trees) into their scene.

It was not part of their Sprint work, but it needs to be noted that Cesium has a https://cesium.com/blog/2021/03/30/cesium-for-unreal-now-available/[plugin for Unreal that on-demand imports 3D geospatial data].

==== Conversion (Scenario 1)

* Timing diagram from InfoDao
* Ecere's work on tiles and LOD
* Simblocks work importing to Unity & Unreal

=== Indoor / Outdoor (Scenario 2)

* Steinbeis' work in the video
* Ecere's work without a game engine

==== Moving models (Scenario 3)

* Limited results
* See Steinbeis & SimBlocks

==== glTF as Modenling Standard (Scenario 4)

* FlightSafety's shuttle model; Materials Variants tree example
* Cesium's metadata texture
* InfoDao's real-time building replacement

==== Other Accomplishments

* Steinbeis create AR app that integrates SensorThings using OGC API's on back-end servers