[[Conclusions]]
== Conclusions


*Introduction*

The ISG Year 2 Sprint begins to layout the path from today's CDB environment with data stored as Shapefiles and models stored in OpenFlight to the future. The participants works suggests a path that is data-similar but feature-richer than today's capabilities. This path is most clearly indicated by enhanced capabilities using glTF models, batch-driven and interactive data conversions, and game engine driven displays.

*Models stored as glTF*

glTF models have the potential to offer a visually richer display. glTF uses physically based rendering (PBR) for its material model. PBR can more accurate depict real-world materials in all wavelengths than the specular model used by OpenFlight. glTF has a large number of extensions that support much of what is needed in a CDB environment. Cesium and FlightSafety demonstrated that development of features not currently supported by glTF is not difficult. FlightSafety has recommended that the CDB Standard define requirements for using glTF models in a near-future version of CDB.

*Data conversions*

Data conversions (and conflation) are time-consuming, non-trivial tasks, that are necessary to support the wide range of missions that the CDB Standard supports. InfoDao proposed batch conversion for long-term and allow real-time/interactive updates as needed in a _Disconnected, Interrupted, Intermittent, Low-Bandwidth_ (DIIL) environment.

*Game engine and XR displays*

SimBlocks.io, Steinbeis, and InfoDao showed how game engines (e.g., Unity or Unreal Engine) can be used to drive the client displays. These engines can be used in desktop, virtual (e.g., headsets), or augmented environments making them one of the most useful client side display drivers. Steinbeis built Android and iOS Augmented and Virtual Reality apps running on phones to display 3D data.

[[conclude]]
*Conclusion*

The path is laid out through data conversion, use of modern model transmission formats, and standard commercial display engines. Travel along the path needs to be well-planned so that the entire community can fully participate and evaluate the progress. Progress towards this goal needs to be at a pace sufficiently fast to get there without leaving anyone or any critical features behind. There is much development to do and specifications to write
