[[Futures]]
== Recommendations for the Future

=== Introduction

=== General Recommendations for Future Sprints

=== Topics of Future Work


=== Notes taken during Participant Report reviews

* General
** Avoid the period around the member's meeting and do not split a Sprint with the member's meeting
** Determine how much of the currently glTF and extension capabilities are needed for geospatial applications and CDB in particular
** Consider allowing use of glTF models in CDB along with OpenFlight with the potential intent of deprecating and removing OpenFlight in the medium/far future
** Work more with moving models and how to store time-based and time-sensitive information. Perhaps this is good work for a cross-over effort with GeoPose.
* External organizations
** Khronos needs to better support community conversion tools or provide a standardized version
** Closely partnet with Khronos to support the identification and development of features necessary to support geospatial applications. 
